CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_status_createdAt_idx" ON "User"("status", "createdAt");
CREATE UNIQUE INDEX "Session_token_key" ON "Session"("token");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Account_userId_idx" ON "Account"("userId");
CREATE UNIQUE INDEX "Account_providerId_accountId_key" ON "Account"("providerId", "accountId");
CREATE INDEX "Verification_identifier_idx" ON "Verification"("identifier");
CREATE UNIQUE INDEX "PointAccount_userId_key" ON "PointAccount"("userId");
CREATE UNIQUE INDEX "PointLedger_idempotencyKey_key" ON "PointLedger"("idempotencyKey");
CREATE INDEX "PointLedger_userId_createdAt_idx" ON "PointLedger"("userId", "createdAt");
CREATE INDEX "PointLedger_taskId_idx" ON "PointLedger"("taskId");
CREATE UNIQUE INDEX "ImageTask_idempotencyKey_key" ON "ImageTask"("idempotencyKey");
CREATE INDEX "ImageTask_userId_createdAt_idx" ON "ImageTask"("userId", "createdAt");
CREATE INDEX "ImageTask_status_createdAt_idx" ON "ImageTask"("status", "createdAt");
CREATE INDEX "ImageTask_type_status_idx" ON "ImageTask"("type", "status");
CREATE UNIQUE INDEX "TaskAsset_objectKey_key" ON "TaskAsset"("objectKey");
CREATE INDEX "TaskAsset_taskId_role_idx" ON "TaskAsset"("taskId", "role");
CREATE UNIQUE INDEX "PricingRule_type_ratio_quality_key" ON "PricingRule"("type", "ratio", "quality");
CREATE INDEX "DailyCheckIn_createdAt_idx" ON "DailyCheckIn"("createdAt");
CREATE UNIQUE INDEX "DailyCheckIn_userId_dateKey_key" ON "DailyCheckIn"("userId", "dateKey");
CREATE INDEX "RedemptionBatch_createdAt_idx" ON "RedemptionBatch"("createdAt");
CREATE UNIQUE INDEX "RedemptionCode_codeHash_key" ON "RedemptionCode"("codeHash");
CREATE INDEX "RedemptionCode_batchId_redeemedAt_idx" ON "RedemptionCode"("batchId", "redeemedAt");
CREATE INDEX "AdminAuditLog_actorId_createdAt_idx" ON "AdminAuditLog"("actorId", "createdAt");
CREATE INDEX "AdminAuditLog_targetType_targetId_idx" ON "AdminAuditLog"("targetType", "targetId");

ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PointAccount" ADD CONSTRAINT "PointAccount_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PointLedger" ADD CONSTRAINT "PointLedger_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PointLedger" ADD CONSTRAINT "PointLedger_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ImageTask"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ImageTask" ADD CONSTRAINT "ImageTask_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskAsset" ADD CONSTRAINT "TaskAsset_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ImageTask"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DailyCheckIn" ADD CONSTRAINT "DailyCheckIn_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RedemptionBatch" ADD CONSTRAINT "RedemptionBatch_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RedemptionCode" ADD CONSTRAINT "RedemptionCode_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "RedemptionBatch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RedemptionCode" ADD CONSTRAINT "RedemptionCode_redeemedById_fkey" FOREIGN KEY ("redeemedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdminAuditLog" ADD CONSTRAINT "AdminAuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
