const SECONDS_PER_MINUTE = 60;

export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 128;
export const EMAIL_OTP_LENGTH = 6;
export const EMAIL_OTP_EXPIRY_MINUTES = 5;
export const EMAIL_OTP_EXPIRES_IN_SECONDS = EMAIL_OTP_EXPIRY_MINUTES * SECONDS_PER_MINUTE;
export const EMAIL_OTP_ALLOWED_ATTEMPTS = 3;
export const EMAIL_OTP_RATE_LIMIT_WINDOW_SECONDS = 60;
export const EMAIL_OTP_RATE_LIMIT_MAX_REQUESTS = 3;
