import { TicketCheck } from "lucide-react";
import { prisma } from "@image-playground/db";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CodeBatchAction } from "./code-batch-action";
import { CodeBatchForm } from "./code-batch-form";

export default async function AdminCodesPage() {
  const batches = await prisma.redemptionBatch.findMany({ include: { _count: { select: { codes: true } }, codes: { where: { redeemedAt: { not: null } }, select: { id: true } } }, orderBy: { createdAt: "desc" } });
  return <div className="grid gap-8"><PageHeader title="兑换码管理" description="创建、下载并管理兑换码批次。兑换码明文只在批次生成后返回一次。" icon={TicketCheck} /><CodeBatchForm /><div className="hidden md:block"><Card className="overflow-hidden shadow-none"><Table className="min-w-[920px]"><TableHeader><TableRow><TableHead>批次</TableHead><TableHead>积分</TableHead><TableHead>已用 / 总量</TableHead><TableHead>过期时间</TableHead><TableHead>状态</TableHead><TableHead>创建时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{batches.map((batch) => <TableRow key={batch.id}><TableCell className="font-semibold">{batch.name}</TableCell><TableCell className="tabular-nums">{batch.pointValue}</TableCell><TableCell className="tabular-nums">{batch.codes.length} / {batch._count.codes}</TableCell><TableCell>{batch.expiresAt?.toLocaleString("zh-CN") ?? "永久"}</TableCell><TableCell><Badge tone={batch.disabledAt ? "error" : "success"}>{batch.disabledAt ? "已停用" : "启用"}</Badge></TableCell><TableCell>{batch.createdAt.toLocaleString("zh-CN")}</TableCell><TableCell><CodeBatchAction batchId={batch.id} disabled={Boolean(batch.disabledAt)} /></TableCell></TableRow>)}</TableBody></Table></Card></div><div className="grid gap-4 md:hidden">{batches.map((batch) => <Card key={batch.id} className="shadow-none"><CardContent className="grid gap-4 p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold">{batch.name}</p><Badge tone={batch.disabledAt ? "error" : "success"}>{batch.disabledAt ? "已停用" : "启用"}</Badge></div><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">每码积分</dt><dd className="mt-1 font-semibold tabular-nums">{batch.pointValue}</dd></div><div><dt className="text-muted-foreground">已用 / 总量</dt><dd className="mt-1 font-semibold tabular-nums">{batch.codes.length} / {batch._count.codes}</dd></div><div className="col-span-2"><dt className="text-muted-foreground">过期时间</dt><dd className="mt-1">{batch.expiresAt?.toLocaleString("zh-CN") ?? "永久"}</dd></div></dl><div className="flex justify-end"><CodeBatchAction batchId={batch.id} disabled={Boolean(batch.disabledAt)} /></div></CardContent></Card>)}</div></div>;
}
